/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ConnectionJDBC;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class Application {
  
  public static void main(String [] args){
	 
	  String urlConnection = "jdbc:mysql://localhost:3306/dio";
	
	 try {
		 Connection conn = DriverManager.getConnection(urlConnection, "root", null);
		System.out.println("Sucesso");
	} catch (SQLException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
		System.out.println("falha");	
	}
	 
	  
  }

}
